# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion_maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venc_patente', models.DateField()),
                ('costo_patente', models.IntegerField()),
                ('soap_costo', models.IntegerField()),
                ('venc_rev_tec', models.DateField()),
                ('costo_rev_tec', models.IntegerField()),
                ('costo_seg_auto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('numero_motor', models.CharField(max_length=45)),
                ('numero_chasis', models.CharField(max_length=45)),
                ('bin', models.CharField(max_length=45)),
                ('patente', models.CharField(max_length=10)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Clasificacion_maquina')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Compania')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('0', 'Teniente de máquina'), ('1', 'OBAC'), ('2', 'Inspector general de máquina'), ('3', 'Comandante')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detalle_maquina',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Maquina'),
        ),
    ]
